2025-01-09 21:57:32,230:Uzduotis_1.py:ERROR:0
Traceback (most recent call last):
  File "c:\Users\Debiliukas\PycharmProjects\PythonProject\Loginimas\Uzduotis_1.py", line 36, in dalyba
    7 / 0
    ~~^~~
ZeroDivisionError: division by zero
